#!/usr/bin/env bash

set -e

if [[ -z "${ORG_DIR}" ]]; then
    ORG_DIR="$(find $HOME/.emacs.d/elpa -maxdepth 1 -type d -regex ".*org-[0-9]*")"
    # -maxdepth *is* a GNUism, but it's been ported everywhere by now.
fi

if [[ -z "${OX_REVEAL_DIR}" ]]; then
    OX_REVEAL_DIR="$(find $HOME/.emacs.d/elpa -maxdepth 1 -type d -regex ".*ox-reveal-[0-9.]*")"
fi

if [[ -d "$ORG_DIR" ]]; then
    emacs -Q --batch \
        --eval "(add-to-list 'load-path \"$ORG_DIR\")" \
        --eval "(add-to-list 'load-path \"$OX_REVEAL_DIR\")" \
        --eval "(require 'org)" \
        --eval "(require 'ox-reveal)" \
        --eval "(setq org-confirm-babel-evaluate nil)" \
        --visit="$1" --funcall org-reveal-export-to-html
else
    echo "No org-mode directory found."
fi
